M48
; DRILL file {KiCad 8.0.4} date 2024-10-21T15:03:47+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-21T15:03:47+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X1.85Y-2.0409
X1.85Y-3.2642
X4.8945Y-2.0409
X4.8945Y-3.2642
M30
