M48
; DRILL file {KiCad 8.0.4} date 2024-10-21T15:09:49+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-21T15:09:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.063Y-2.4567
X3.063Y-3.6929
X6.126Y-2.4488
X6.126Y-3.7087
M30
